import {
  BookingClassFactory,
  BookingsCollectionClassFactory,
  RouteVersionClassFactory,
  RouteVersionsCollectionClassFactory,
  RouteClassFactory,
  VariantClassFactory,
  VariantsCollectionClassFactory,
  VariantPointClassFactory,
  VariantPointsCollectionClassFactory,
  VehicleScheduleClassFactory,
  VehicleScheduleOrRouteVersionClassFactory,
  TripClassFactory,
  TripPointClassFactory,
  TripOrVariantClassFactory,
  TripOrVariantPointClassFactory,
  VehicleSchedulesCollectionClassFactory,
  TripsCollectionClassFactory,
  TripPointsCollectionClassFactory,
  PlaceClassFactory,
  PlacesCollectionClassFactory,
  VscincloirClassFactory,
  VscincloirsCollectionClassFactory,
  NetworkEventClassFactory,
  NetworkEventsCollectionClassFactory,
  VehicleUnitClassFactory,
  VehicleUnitsCollectionClassFactory,
  BlockClassFactory,
  BlocksCollectionClassFactory,
  BlkvehuoirClassFactory,
  BlkvehuoirsCollectionClassFactory,
  BlockActivityClassFactory,
  BlockActivitiesCollectionClassFactory,
  VehicleStandbyClassFactory,
  VehicleStandbysCollectionClassFactory,
  MaintenanceClassFactory,
  MaintenancesCollectionClassFactory,
  TripTpClassFactory,
  TripTpsCollectionClassFactory,
  TripvehgrpspecClassFactory,
  TripvehgrpspecsCollectionClassFactory,
  TripShiftClassFactory,
  TripShiftsCollectionClassFactory,
  ConsistChangeClassFactory,
  ConsistChangesCollectionClassFactory,
  OvernightLinkClassFactory,
  OvernightLinksCollectionClassFactory,
  RunTimeVersionClassFactory,
  RunTimeVersionsCollectionClassFactory,
  RunTimeClassFactory,
  RunTimesCollectionClassFactory,
  LoadTimeClassFactory,
  LoadTimesCollectionClassFactory,
  VehicleTaskClassFactory,
  VehicleTasksCollectionClassFactory,
  BlockSectionClassFactory,
  BlockSectionsCollectionClassFactory,
  BookingCalendarClassFactory,
  BookingCalendarsCollectionClassFactory,
  BookingCalendarDateClassFactory,
  BookingCalendarDatesCollectionClassFactory,
  SchedulingUnitDateClassFactory,
  SchedulingUnitDatesCollectionClassFactory,
  ServiceContextClassFactory,
  ServiceContextsCollectionClassFactory,
  ServiceContextDayClassFactory,
  ServiceContextDaysCollectionClassFactory,
  ServiceContextIntervalClassFactory,
  ServiceContextIntervalsCollectionClassFactory,
  ServiceContextParentClassFactory,
  ServiceContextParentsCollectionClassFactory,
  ServiceContextWeekClassFactory,
  ServiceContextWeeksCollectionClassFactory,
  ServiceEvolutionClassFactory,
  ServiceEvolutionsCollectionClassFactory,
  ServiceEvolutionPeriodClassFactory,
  ServiceEvolutionPeriodsCollectionClassFactory,
  ServiceEvolutionPeriodSchedulesBookingClassFactory,
  ServiceEvolutionPeriodSchedulesBookingsCollectionClassFactory,
  ServiceDefinitionClassFactory,
  ServiceDefinitionsCollectionClassFactory,
  SdefSchedulingUnitClassFactory,
  SdefSchedulingUnitsCollectionClassFactory,
  SchedulingUnitClassFactory,
  SchedulingUnitsCollectionClassFactory,
  TrainPathClassFactory,
  TrainPathsGeneralInfoClassFactory,
  TrainPathsCollectionClassFactory,
  TrainPathVariantClassFactory,
  TrainPathVariantsCollectionClassFactory,
  TrainPathVariantPointClassFactory,
  TrainPathVariantPointsCollectionClassFactory,
  TrainPathVariantDateClassFactory,
  TrainPathVariantDatesCollectionClassFactory,
  TripOrVariantSectionClassFactory,
  TripOrVariantSectionsCollectionClassFactory,
  BoundingBoxClassFactory,
  DataFileClassFactory,
  DataFilesCollectionClassFactory,
  AdjacentLinkClassFactory,
  NetworkMapClassFactory,
  NetworkMapsCollectionClassFactory,
  NetworkNodeClassFactory,
  NetworkNodesCollectionClassFactory,
  NetworkEdgeClassFactory,
  NetworkEdgesCollectionClassFactory,
  NetworkClassFactory,
  NetworksCollectionClassFactory,
  NetworkSectionClassFactory,
  NetworkSectionsCollectionClassFactory,
  RoutesCollectionClassFactory,
  SchedulingUnitRouteClassFactory,
  SchedulingUnitRoutesCollectionClassFactory,
} from "./rawIndex";

export const DefaultClassFactoryByEntityClassKey = {
  BoundingBoxClassFactory,
  DataFileClassFactory,
  DataFilesCollectionClassFactory,

  TripOrVariantPointClassFactory,

  VariantPointClassFactory,
  VariantPointsCollectionClassFactory,

  TripOrVariantClassFactory,

  VariantClassFactory,
  VariantsCollectionClassFactory,
  RouteClassFactory,
  RoutesCollectionClassFactory,

  TripPointClassFactory,
  TripPointsCollectionClassFactory,
  TripTpClassFactory,
  TripTpsCollectionClassFactory,
  TripvehgrpspecClassFactory,
  TripvehgrpspecsCollectionClassFactory,
  TripShiftClassFactory,
  TripShiftsCollectionClassFactory,

  BlockActivityClassFactory,
  BlockActivitiesCollectionClassFactory,

  TripClassFactory,
  TripsCollectionClassFactory,

  BlkvehuoirClassFactory,
  BlkvehuoirsCollectionClassFactory,

  BlockClassFactory,
  BlocksCollectionClassFactory,

  NetworkEventClassFactory,
  NetworkEventsCollectionClassFactory,

  VehicleUnitClassFactory,
  VehicleUnitsCollectionClassFactory,

  VehicleStandbyClassFactory,
  VehicleStandbysCollectionClassFactory,
  MaintenanceClassFactory,
  MaintenancesCollectionClassFactory,
  ConsistChangeClassFactory,
  ConsistChangesCollectionClassFactory,
  OvernightLinkClassFactory,
  OvernightLinksCollectionClassFactory,

  VehicleScheduleOrRouteVersionClassFactory,
  RouteVersionClassFactory,
  RouteVersionsCollectionClassFactory,
  VscincloirClassFactory,
  VscincloirsCollectionClassFactory,

  VehicleTaskClassFactory,
  VehicleTasksCollectionClassFactory,
  BlockSectionClassFactory,
  BlockSectionsCollectionClassFactory,

  VehicleScheduleClassFactory,
  VehicleSchedulesCollectionClassFactory,

  RunTimeClassFactory,
  RunTimesCollectionClassFactory,
  LoadTimeClassFactory,
  LoadTimesCollectionClassFactory,
  RunTimeVersionClassFactory,
  RunTimeVersionsCollectionClassFactory,

  BookingClassFactory,
  BookingsCollectionClassFactory,
  PlaceClassFactory,
  PlacesCollectionClassFactory,

  SchedulingUnitDateClassFactory,
  SchedulingUnitDatesCollectionClassFactory,

  BookingCalendarDateClassFactory,
  BookingCalendarDatesCollectionClassFactory,

  ServiceContextDayClassFactory,
  ServiceContextDaysCollectionClassFactory,
  ServiceContextIntervalClassFactory,
  ServiceContextIntervalsCollectionClassFactory,
  ServiceContextParentClassFactory,
  ServiceContextParentsCollectionClassFactory,
  ServiceContextWeekClassFactory,
  ServiceContextWeeksCollectionClassFactory,

  ServiceEvolutionPeriodSchedulesBookingClassFactory,
  ServiceEvolutionPeriodSchedulesBookingsCollectionClassFactory,

  ServiceEvolutionPeriodClassFactory,
  ServiceEvolutionPeriodsCollectionClassFactory,

  ServiceContextClassFactory,
  ServiceContextsCollectionClassFactory,

  ServiceEvolutionClassFactory,
  ServiceEvolutionsCollectionClassFactory,

  BookingCalendarClassFactory,

  SchedulingUnitRouteClassFactory,
  SchedulingUnitRoutesCollectionClassFactory,

  SchedulingUnitClassFactory,
  SchedulingUnitsCollectionClassFactory,
  SdefSchedulingUnitClassFactory,
  SdefSchedulingUnitsCollectionClassFactory,

  ServiceDefinitionClassFactory,
  ServiceDefinitionsCollectionClassFactory,

  TrainPathVariantPointClassFactory,
  TrainPathVariantPointsCollectionClassFactory,
  TrainPathVariantDateClassFactory,
  TrainPathVariantDatesCollectionClassFactory,

  TrainPathVariantClassFactory,
  TrainPathVariantsCollectionClassFactory,
  TrainPathsGeneralInfoClassFactory,

  TrainPathClassFactory,
  TrainPathsCollectionClassFactory,

  BookingCalendarsCollectionClassFactory,

  TripOrVariantSectionClassFactory,
  TripOrVariantSectionsCollectionClassFactory,

  NetworkNodeClassFactory,
  NetworkNodesCollectionClassFactory,
  NetworkEdgeClassFactory,
  NetworkEdgesCollectionClassFactory,
  NetworkSectionClassFactory,
  NetworkSectionsCollectionClassFactory,

  AdjacentLinkClassFactory,
  NetworkMapClassFactory,
  NetworkMapsCollectionClassFactory,
  NetworkClassFactory,
  NetworksCollectionClassFactory,
};
